# CyberPanel / OpenLiteSpeed: en el sitio (ej. atalaya.SU-DOMINIO) > vHost Conf, agregue:
extprocessor atalaya {
  type                    proxy
  address                 127.0.0.1:3950
  maxConns                100
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}
context / {
  type                    proxy
  handler                 atalaya
  addDefaultCharset       off
}
